pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'

- script: docker build -t integration_test .
  displayName: 'docker build'
  continueOnError: false

- script: docker run integration_test bash integration_test.sh
  displayName: 'integration test'
  continueOnError: false