
jobs:

- job: 'Setup'
  pool:
    vmImage: 'Ubuntu 16.04'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  steps:
  - script: sudo apt install python3-pip --reinstall -y
    displayName: 'install pip'
    continueOnError: false
  - script: pip install --upgrade pip  
    displayName: 'upgrade pip'
    continueOnError: false
  - script: |
      python setup.py sdist bdist_wheel
    displayName: 'package artifacts'
    continueOnError: false

- job: 'Test'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: docker build -t integration_test -f test.Dockerfile .
    displayName: 'docker build'
    continueOnError: false

  - script: docker run integration_test
    displayName: 'integration test'
    continueOnError: false

- job: 'Publish'
  dependsOn: 'Test'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: 'twine upload dist/*'
    displayName: 'publish-python package'
    continueOnError: true