trigger:
  branches:
    include:
    - release
  paths:
    include:
    - ktext/

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'

- script: |
    python -m pip install --upgrade pip  
    pip install twine wheel
    python setup.py sdist bdist_wheel
  displayName: 'install dependencies'

- script: 'twine upload dist/*'
  displayName: 'publish-python package'