pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'

jobs:
- job: Test
  steps:
  - script: docker build -t integration_test .
    displayName: 'docker build'
    continueOnError: false
  - script: docker run integration_test bash integration_test.sh
    displayName: 'integration test'
    continueOnError: false
- job: Publish
  dependsOn: Test
  steps:
  - script: |
      python -m pip install --upgrade pip  
      pip install twine wheel
      python setup.py sdist bdist_wheel
    displayName: 'install dependencies'
    continueOnError: false
  - script: 'twine upload dist/*'
    displayName: 'publish-python package'
    continueOnError: true